In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix

In [2]:
m = 1000
n = 5
k = 6

X, y, center = make_blobs(
    n_samples=m,
    n_features=n,
    centers=k,
    cluster_std=0.45,
    random_state=12022, return_centers=True
)

# ILP Results

Imported from `ilp_blobs_results.txt`

In [3]:
df_ilp = pd.read_csv('ilp_blobs_results.txt')

In [4]:
ilp_clusters = df_ilp[' Class'].unique()
ilp_clusters

array([195, 459, 583, 467, 799, 592])

In [5]:
ilp_dict = {
    ilp_clusters[0]:0,
    ilp_clusters[1]:1,
    ilp_clusters[3]:2,
    ilp_clusters[5]:3,
    ilp_clusters[2]:4,
    ilp_clusters[4]:5,
}

In [6]:
df_ilp[2] = df_ilp[' Class'].replace(ilp_dict)

In [7]:
confusion_matrix(df_ilp[2], y)

array([[167,   0,   0,   0,   0,   0],
       [  0, 167,   0,   0,   0,   0],
       [  0,   0, 167,   0,   0,   0],
       [  0,   0,   0, 167,   0,   0],
       [  0,   0,   0,   0, 166,   0],
       [  0,   0,   0,   0,   0, 166]])

# MST results

Imported from `heu_blobs_results.txt`

In [8]:
subgraph0 = [0, 1, 4, 518, 519, 520, 522, 15, 530, 534, 24, 27, 28, 30, 41, 553, 43, 555, 46, 564, 567, 61, 576, 75, 77, 592, 593, 82, 83, 84, 88, 602, 604, 606, 100, 103, 619, 111, 629, 121, 124, 128, 133, 139, 142, 657, 145, 660, 152, 673, 675, 165, 179, 693, 183, 184, 188, 701, 702, 194, 197, 198, 709, 720, 722, 211, 725, 213, 727, 217, 219, 220, 227, 228, 742, 234, 238, 761, 765, 768, 261, 774, 775, 263, 266, 785, 275, 788, 281, 288, 802, 804, 811, 305, 306, 309, 823, 829, 834, 836, 843, 336, 337, 339, 855, 860, 863, 864, 874, 372, 884, 375, 889, 890, 891, 894, 382, 387, 900, 390, 905, 913, 916, 405, 406, 918, 408, 917, 410, 919, 924, 925, 923, 928, 416, 931, 420, 934, 935, 426, 430, 946, 947, 437, 950, 968, 969, 971, 459, 972, 463, 464, 469, 470, 984, 986, 987, 475, 989, 994, 999, 494, 496, 499, 503, 508, 511]
subgraph1 = [2, 8, 12, 16, 528, 17, 531, 535, 537, 538, 35, 37, 549, 38, 40, 45, 562, 566, 572, 574, 65, 67, 73, 74, 587, 590, 594, 596, 86, 599, 90, 91, 92, 608, 609, 611, 99, 612, 613, 101, 106, 116, 632, 120, 634, 636, 638, 126, 640, 645, 646, 135, 649, 137, 663, 151, 155, 668, 671, 166, 678, 681, 688, 176, 182, 189, 190, 195, 708, 199, 201, 716, 205, 719, 214, 216, 731, 221, 224, 737, 739, 233, 244, 762, 250, 255, 767, 258, 259, 262, 265, 274, 277, 797, 286, 800, 805, 294, 298, 299, 300, 813, 816, 826, 318, 832, 833, 835, 324, 325, 330, 333, 335, 853, 343, 346, 858, 348, 349, 352, 353, 355, 360, 361, 364, 877, 878, 370, 371, 373, 895, 384, 899, 902, 391, 394, 906, 912, 915, 404, 921, 926, 927, 930, 423, 942, 431, 955, 444, 957, 450, 963, 964, 458, 461, 973, 975, 979, 468, 981, 988, 990, 996, 997, 495, 498, 501]
subgraph4 = [3, 6, 9, 526, 527, 536, 541, 542, 33, 545, 554, 558, 559, 50, 51, 53, 568, 56, 58, 57, 62, 64, 579, 582, 583, 585, 589, 80, 81, 598, 87, 605, 95, 98, 610, 109, 624, 625, 631, 122, 641, 131, 643, 134, 650, 141, 656, 661, 662, 150, 664, 153, 665, 680, 171, 173, 686, 175, 690, 694, 698, 191, 192, 705, 707, 712, 713, 202, 715, 204, 212, 726, 733, 736, 738, 740, 741, 743, 235, 236, 240, 243, 755, 758, 247, 759, 763, 764, 254, 777, 267, 780, 269, 270, 786, 792, 793, 794, 801, 803, 296, 810, 302, 815, 303, 822, 314, 827, 828, 831, 837, 328, 329, 842, 331, 841, 845, 850, 854, 344, 857, 870, 871, 872, 365, 367, 881, 885, 374, 887, 898, 389, 392, 398, 910, 400, 914, 409, 922, 412, 932, 936, 424, 428, 940, 945, 434, 948, 951, 443, 959, 449, 962, 961, 966, 970, 974, 471, 991, 993, 482, 486, 487, 490, 491, 510]
subgraph2 = [513, 5, 529, 19, 532, 21, 23, 25, 540, 29, 31, 543, 34, 550, 552, 44, 557, 556, 47, 560, 561, 571, 577, 578, 69, 71, 76, 78, 79, 595, 93, 97, 616, 107, 621, 622, 113, 630, 633, 129, 642, 136, 138, 651, 652, 655, 144, 154, 666, 667, 670, 160, 672, 161, 674, 162, 676, 170, 684, 178, 691, 180, 695, 697, 185, 186, 699, 700, 704, 711, 207, 208, 721, 724, 728, 732, 735, 229, 230, 231, 239, 242, 754, 757, 246, 252, 766, 257, 769, 773, 776, 778, 782, 272, 273, 276, 282, 285, 291, 293, 808, 297, 814, 304, 308, 821, 323, 327, 334, 847, 848, 851, 340, 859, 862, 865, 357, 366, 879, 368, 882, 886, 378, 380, 383, 385, 386, 388, 903, 393, 908, 402, 413, 417, 933, 422, 937, 425, 427, 943, 944, 435, 954, 447, 960, 451, 452, 456, 457, 460, 462, 465, 466, 982, 983, 985, 474, 476, 992, 480, 995, 485, 489, 500, 504, 506, 507]
subgraph5 = [512, 514, 515, 516, 7, 10, 11, 524, 14, 20, 22, 26, 544, 546, 547, 548, 36, 551, 63, 575, 66, 68, 581, 70, 72, 586, 588, 89, 603, 94, 96, 617, 105, 618, 110, 112, 626, 114, 628, 117, 118, 119, 637, 127, 132, 648, 140, 654, 658, 147, 148, 669, 157, 163, 167, 682, 683, 687, 689, 692, 181, 696, 187, 703, 193, 706, 196, 200, 714, 203, 210, 215, 730, 218, 222, 734, 225, 226, 744, 745, 746, 749, 241, 245, 248, 760, 251, 256, 771, 779, 781, 783, 787, 789, 790, 280, 795, 283, 284, 798, 799, 796, 289, 290, 292, 806, 807, 809, 812, 818, 307, 311, 312, 315, 317, 830, 320, 321, 840, 844, 846, 338, 341, 856, 861, 351, 866, 356, 869, 358, 359, 876, 369, 888, 376, 379, 892, 381, 901, 904, 395, 909, 399, 401, 403, 929, 419, 941, 429, 438, 446, 453, 454, 455, 976, 977, 473, 477, 481, 483, 484, 998, 488, 493, 497, 502]
subgraph3 = [517, 521, 523, 525, 13, 18, 533, 539, 32, 39, 42, 48, 49, 563, 52, 565, 54, 55, 569, 570, 59, 60, 573, 580, 584, 591, 597, 85, 600, 601, 607, 614, 102, 104, 615, 108, 620, 623, 115, 627, 635, 123, 125, 639, 130, 644, 647, 653, 143, 146, 659, 149, 156, 158, 159, 164, 677, 679, 168, 169, 172, 685, 174, 177, 710, 717, 206, 718, 209, 723, 729, 223, 232, 747, 748, 237, 750, 751, 752, 753, 756, 249, 253, 770, 260, 772, 264, 268, 271, 784, 278, 279, 791, 287, 295, 301, 817, 819, 820, 310, 824, 313, 825, 316, 319, 322, 838, 839, 326, 332, 849, 852, 342, 345, 347, 350, 354, 867, 868, 873, 362, 363, 875, 880, 883, 377, 893, 896, 897, 907, 396, 397, 911, 407, 920, 411, 414, 415, 418, 421, 938, 939, 432, 433, 436, 949, 439, 952, 953, 442, 440, 956, 441, 958, 445, 448, 965, 967, 978, 467, 980, 472, 478, 479, 492, 505, 509]

In [9]:
df_class = pd.DataFrame(y)
df_class.loc[subgraph0, 1] = int(0)
df_class.loc[subgraph1, 1] = int(1)
df_class.loc[subgraph2, 1] = int(2)
df_class.loc[subgraph3, 1] = int(3)
df_class.loc[subgraph4, 1] = int(4)
df_class.loc[subgraph5, 1] = int(5)

In [10]:
confusion_matrix(df_class[0], df_class[1])

array([[167,   0,   0,   0,   0,   0],
       [  0, 167,   0,   0,   0,   0],
       [  0,   0, 167,   0,   0,   0],
       [  0,   0,   0, 167,   0,   0],
       [  0,   0,   0,   0, 166,   0],
       [  0,   0,   0,   0,   0, 166]])